insert into engdb.status (id, status) values (1, 'Неповні');
insert into engdb.status (id, status) values (2, 'Повні');
insert into engdb.status (id, status) values (3, 'Не перевірен');
insert into engdb.status (id, status) values (4, 'Перевірені');
insert into engdb.status (id, status) values (5, 'Закрито');

insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (1795, null, '0,254  (0,01 in)', '0,254  (0,01 in)', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (1796, null, '0,508 (0,02 in)', '0,508 (0,02 in)', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (1797, null, 0.762, 0.762, 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (1798, null, 1.016, 1.016, 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (1799, null, 'Std', 'Std', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (1800, null, 0.127, 0.127, 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (1801, null, '0,508   (0,02 in)', '0,508   (0,02 in)', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (1802, null, 0.25, 0.25, 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (1803, null, 0.5, 0.5, 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (1804, null, 0.381, 0.381, 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (1805, null, 0.75, 0.75, 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (1806, null, 1.27, 1.27, 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (1807, null, 1.0, 1.0, 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (234, null, 'Длина гильзы', 'Длина гильзы', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (245, null, 'Коленвал', 'Коленвал', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (1, null, 'значення', 'знач.', 1, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (237, null, 'Диаметр втулки', 'Диаметр втулки', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (244, null, 'Общие параметры', 'Общие параметры', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (246, null, 'Коренные шейки', 'Коренные шейки', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (247, null, 'Шатунные шейки', 'Шатунные шейки', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (252, null, 'Масляный зазор', 'Масляный зазор', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (258, null, 'Опора 6', 'Опора 6', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (259, null, 'Опора 7', 'Опора 7', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (260, null, 'Диаметр коренной шейки', 'Диаметр КШ', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (264, null, 'Ширина опорной шейки', 'Ширина опорной шейки', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (265, null, 'Ширина остальных шеек', 'Ширина остальных шеек', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (266, null, 'Радиус галтели', 'Радиус галтели', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (267, null, 'Диаметр шатунной шейки', 'Диаметр ШШ', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (268, null, 'Ширина шатунной шейки', 'Ширина ШШ', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (269, null, 'Шатуны', 'Шатуны', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (277, null, 'Нижняя головка', 'Нижняя головка', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (278, null, 'Верхняя головка', 'Верхняя головка', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (280, null, 'Диаметр отверстия под палец', 'Диаметр отверстия под палец', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (282, null, 'Диаметр пальца', 'Диаметр пальца', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (291, null, 'Головка блока цилиндров', 'ГБЦ', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (295, null, 'Клапан', 'Клапан', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (235, null, 'Диаметр бурта в БЦ', 'Диаметр бурта в БЦ', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (296, null, 'Группа', 'Группа', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (302, null, 'Направляющая втулка клапана', 'Направляющая втулка клапана', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (236, null, 'Длина болта', 'Длина болта', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (238, null, 'Натяг втулки', 'Натяг втулки', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (239, null, 'Осевой зазор', 'Осевой зазор', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (240, null, 'Прогиб р/вала', 'Прогиб р/вала', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (249, null, 'Дисбаланс', 'Дисбаланс', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (250, null, 'Радиус кривошипа', 'Радиус кривошипа', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (251, null, 'Прогиб', 'Прогиб', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (253, null, 'Опора 1', 'Опора 1', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (254, null, 'Опора 2', 'Опора 2', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (255, null, 'Опора 3', 'Опора 3', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (256, null, 'Опора 4', 'Опора 4', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (257, null, 'Опора 5', 'Опора 5', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (194, null, 'Коленвал', 'Коленвал', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (195, null, 'Гильзы', 'Гильзы', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (309, null, 'Седла', 'Седла', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (261, null, 'Рем.р. 0,10', '0,10', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (270, null, 'Межосевое расстояние', 'Межосевое расстояние', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (271, null, 'Вес', 'Вес', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (272, null, 'Класс А', 'Класс А', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (273, null, 'Класс В', 'Класс В', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (274, null, 'Класс С', 'Класс С', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (275, null, 'М11', 'М11', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (276, null, 'Изгиб', 'Изгиб', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (279, null, 'Рем.размер', 'Рем.размер', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (281, null, 'Диаметр втулки наружный', 'Диаметр втулки наружный', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (292, null, 'Высота ГБЦ', 'Высота ГБЦ', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (294, null, 'Материал', 'Материал', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (293, null, 'Допустимый прогиб', 'Допустимый прогиб', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (297, null, 'Диаметр ножки', 'Диаметр ножки', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (298, null, 'Длина', 'Длина', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (299, null, 'Диаметр тарелки', 'Диаметр тарелки', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (300, null, 'Угол раб.фаски', 'Угол раб.фаски', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (301, null, 'Толщина цил.части тарелки', 'Толщина цил.части тарелки', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (303, null, 'Натяг', 'Натяг', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (304, null, 'Диаметр отверстия в ГБЦ', 'Диаметр отверстия в ГБЦ', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (305, null, 'Диаметр втулки наружный', 'Диаметр втулки наружный', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (306, null, 'Длинна втулки', 'Длинна втулки', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (307, null, 'Выступание втулки', 'Выступание втулки', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (308, null, 'Внутренний диаметр', 'Внутренний диаметр', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (311, null, 'Диаметр седла внутренний', 'Диаметр седла внутренний', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (312, null, 'Диаметр седла наружный', 'Диаметр седла наружный', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (193, null, 'Блок цилиндров', 'Блок цилиндров', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (316, null, 'Комбинация углов', 'Комбинация углов', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (336, null, 'М12', 'М12', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (262, null, 'Рем.р. 1,00', '1,00', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (310, null, 'Высота седла', 'Высота седла', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (313, null, 'Вылет штока', 'Вылет штока', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (314, null, 'Залегание / выступание', 'Залегание / выступание', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (315, null, 'Ширина раб.фаски', 'Ширина раб.фаски', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (317, null, '№ 2', '№ 2', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (318, null, '№ 3', '№ 3', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (319, null, '№ 4', '№ 4', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (320, null, '№ 5', '№ 5', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (321, null, '№ 6', '№ 6', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (322, null, '№ 7', '№ 7', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (323, null, 'Впуск', 'Впуск', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (324, null, 'Выпуск', 'Выпуск', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (329, null, 'Рем.размер №1', 'Рем.размер №1', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (330, null, 'Рем.размер №2', 'Рем.размер №2', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (331, null, 'Рем.размер №3', 'Рем.размер №3', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (332, null, 'Зазор', 'Зазор', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (333, null, 'Рем.р. 0,30', '0,30', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (334, null, 'Рем.р. 0,60', '0,60', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (263, '2020-08-19', 'Осевой зазор', 'Осевой зазор', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (248, null, 'Твёрдость', 'Твёрдость', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (335, null, 'Рем.р. 0,90', '0,90', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (337, null, 'М20', 'М20', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (340, null, 'Рем.р. 0,20', '0,20', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (341, null, 'Рем.р. 0,40', '0,40', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (196, null, 'Цилиндры', 'Цилиндры', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (197, null, 'Постель коленвала', 'Постель к/вала', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (198, null, 'Постель распредвала', 'Постель р/вала', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (200, null, 'Глубина бурта в БЦ', 'Глубина бурта в БЦ', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (199, null, 'Выступание гильзы', 'Выступание гильзы', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (201, null, 'Высота бурта гильзы', 'Высота бурта гильзы', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (211, null, 'Рем.р. 0,50', '0,5', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (202, null, 'Наружный диаметр гильзы', 'Наружный диаметр гильзы', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (205, null, 'Отверстие в БЦ под гильзу', 'Отверстие в БЦ под гильзу', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (207, null, 'Натяг/зазор', 'Натяг/зазор', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (213, null, 'Диаметр цилиндра', 'Диаметр цилиндра', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (214, null, 'Диаметр поршня', 'Диаметр поршня', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (216, null, 'Высота БЦ', 'Высота БЦ', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (224, null, 'Бугеля', 'Бугеля', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (225, null, 'Длинные плиты', 'Длинные плиты', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (226, null, 'Короткие плиты', 'Короткие плиты', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (227, null, 'Диаметр отверстия', 'Диаметр отверстия', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (228, null, 'Диаметры отверстий под втулки', 'Диаметры отверстий под втулки', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (229, null, 'Диаметр постели р/вала', 'Диаметр постели р/вала', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (231, null, 'Остальные', 'Остальные', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (232, null, 'Диаметр р/вала', 'Диаметр р/вала', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (203, null, 'Натяг', 'Натяг', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (204, null, 'Диаметр бурта гильзы', 'Диаметр бурта гильзы', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (206, null, 'Верх', 'Верх', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (208, null, 'Низ', 'Низ', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (209, null, 'Рем.р. Std', 'std', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (212, null, 'Рем.р. 0,75', '0,75', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (215, null, 'Тепловой зазор', 'Тепловой зазор', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (217, null, 'Ширина опоры', 'Ширина опоры', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (218, null, 'Момент затяжки', 'Момент затяжки', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (219, null, 'М8', 'М8', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (220, null, 'М6', 'М6', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (221, null, 'М7', 'М7', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (222, null, 'М9', 'М9', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (223, null, 'М10', 'М10', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (230, null, '№ 1', '№ 1', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (345, null, '0,25', '0,25', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (346, '2020-08-06', 'Рем.р. 0,25', '0,25', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (210, null, '0,45', 'Рем.р. 0,45', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (395, '2020-08-11', 's', 'sss', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (396, '2020-08-11', '', '', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (445, '2020-08-12', 'Твёрдость', 'Твёрдость', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (495, null, 'Коллектор', 'Коллектор', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (545, null, 'Коллектор', 'Коллектор', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (546, null, 'Коллектор', 'Коллектор', 2, 'false');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (547, '2020-08-14', 'test', 'test', 2, 'true');
insert into engdb.parameter_names (id, date_create, full_name, name, status_fk, tree_root) values (595, null, 'ос. зазор', 'осевой зазор', 2, 'true');
